// ═══════════════════════════════════════════════════════
// 365 DATOS CURIOSOS SOBRE ASTRONOMÍA Y ASTROLOGÍA
// Rotan automáticamente según el día del año
// Con rigor científico y toque místico 💅🏼🌙
// ═══════════════════════════════════════════════════════

export const DATOS_CURIOSOS = [
  // ENERO
  { emoji: '🌙', texto: 'La Luna se aleja de la Tierra aproximadamente 3.8 centímetros por año. En unos 600 millones de años, los eclipses solares totales serán imposibles porque la Luna estará demasiado lejos.' },
  { emoji: '⭐', texto: 'La luz que ves de la estrella más cercana al Sol, Próxima Centauri, salió de ella hace 4.24 años. Cuando la mirás, estás viendo el pasado.' },
  { emoji: '🪐', texto: 'Saturno tiene una densidad tan baja que flotaría en agua. Es el único planeta del sistema solar con esa propiedad.' },
  { emoji: '🌑', texto: 'La Luna no tiene atmósfera, por eso las huellas de los astronautas del Apolo seguirán intactas durante millones de años.' },
  { emoji: '☀️', texto: 'El Sol representa el 99.86% de toda la masa del sistema solar. Todos los planetas, lunas, asteroides y cometas juntos son apenas el 0.14%.' },
  { emoji: '🌊', texto: 'Las mareas oceánicas son causadas principalmente por la gravedad de la Luna. El Sol también influye, pero su efecto es menos de la mitad que el lunar.' },
  { emoji: '✨', texto: 'Hay más estrellas en el universo observable que granos de arena en todas las playas de la Tierra. Se estima en 2 × 10²³ estrellas.' },
  { emoji: '🔴', texto: 'Marte tiene el volcán más grande del sistema solar: el Olympus Mons, con 21 km de altura y 600 km de diámetro. El Everest apenas llega a 8.8 km.' },
  { emoji: '💫', texto: 'Una cucharadita de materia de estrella de neutrones pesa aproximadamente mil millones de toneladas — más que el Monte Everest.' },
  { emoji: '🌌', texto: 'La Vía Láctea y la galaxia de Andrómeda colisionarán en aproximadamente 4.500 millones de años, formando una nueva galaxia elíptica.' },
  { emoji: '🌙', texto: 'En astrología babilónica, la Luna era considerada un dios masculino llamado Nanna o Sin, no femenino. La asociación de la Luna con lo femenino es más tardía.' },
  { emoji: '☿', texto: 'Mercurio no tiene lunas ni anillos. Es, junto a Venus, uno de los únicos planetas del sistema solar en esa condición.' },
  { emoji: '🌟', texto: 'Las estrellas de neutrones giran hasta 716 veces por segundo. Son los objetos que rotan más rápido conocidos en el universo.' },
  { emoji: '🌕', texto: 'La cara oculta de la Luna nunca es visible desde la Tierra porque la Luna tarda el mismo tiempo en rotar sobre su eje que en orbitar nuestro planeta. Esto se llama rotación sincrónica.' },
  { emoji: '🪐', texto: 'Los anillos de Saturno tienen solo 10 metros de grosor en promedio, pero se extienden 282.000 km. Es como una hoja de papel del tamaño de un estadio.' },
  { emoji: '⚡', texto: 'Los rayos en Júpiter son hasta 1000 veces más poderosos que los de la Tierra. Las tormentas en el gigante gaseoso pueden durar siglos.' },
  { emoji: '🌙', texto: 'La palabra "lunático" viene del latín "lunaticus", que significa "afectado por la luna". Durante siglos se creyó que la Luna llena causaba locura.' },
  { emoji: '💎', texto: 'Se cree que en el interior de Neptuno y Urano llueven diamantes literales, formados por la presión extrema que cristaliza el carbono del metano.' },
  { emoji: '🔭', texto: 'Galileo fue el primero en observar las lunas de Júpiter en 1610, prueba directa de que no todo giraba alrededor de la Tierra.' },
  { emoji: '🌠', texto: 'Los meteoritos que caen en la Tierra tienen miles de millones de años. Cuando sostenés uno, estás tocando material del origen del sistema solar.' },
  { emoji: '☀️', texto: 'La energía que el Sol libera en una sola segunda equivale a toda la energía que consumiría la humanidad durante 1 millón de años.' },
  { emoji: '🌙', texto: 'En muchas culturas indígenas americanas, la Luna tiene 13 ciclos por año. El calendario lunar de 13 meses es más preciso para seguir las estaciones agrícolas.' },
  { emoji: '🪐', texto: 'Júpiter actúa como un "escudo" gravitacional para la Tierra, atrayendo o deflectando muchos asteroides y cometas que de otro modo nos impactarían.' },
  { emoji: '🌌', texto: 'La materia oscura compone el 27% del universo, pero no emite, absorbe ni refleja luz. Solo la detectamos por sus efectos gravitacionales.' },
  { emoji: '⭐', texto: 'Betelgeuse, la estrella roja del hombro de Orión, podría explotar en cualquier momento como supernova. Cuando lo haga, será visible de día desde la Tierra.' },
  { emoji: '🌕', texto: 'La Luna tiene terremotos (lunamotos) que pueden durar hasta una hora. Los de la Tierra duran segundos porque el agua amortigua las vibraciones.' },
  { emoji: '🔴', texto: 'La Gran Mancha Roja de Júpiter es una tormenta que lleva activa al menos 350 años. Está disminuyendo de tamaño desde el siglo XIX.' },
  { emoji: '💫', texto: 'Los agujeros negros no "succionan" las cosas como aspiradoras. Si el Sol se convirtiera en agujero negro, la Tierra seguiría en la misma órbita.' },
  { emoji: '🌙', texto: 'El ciclo menstrual humano promedio de 28 días tiene una correlación notable con el ciclo lunar de 29.5 días, aunque no hay evidencia científica de causalidad.' },
  { emoji: '✨', texto: 'Cuando mirás el cielo nocturno, estás viendo el universo en distintos momentos del pasado. Cada estrella es una ventana temporal diferente.' },
  { emoji: '🌟', texto: 'El universo tiene aproximadamente 13.800 millones de años. En ese tiempo, la luz ha viajado 46.000 millones de años luz en todas direcciones — el universo observable.' },

  // FEBRERO
  { emoji: '🌙', texto: 'Las mareas no solo afectan los océanos. La corteza terrestre también sube y baja hasta 30 centímetros bajo la influencia gravitacional de la Luna.' },
  { emoji: '⭐', texto: 'La estrella Sirio, la más brillante del cielo nocturno, era tan importante para los antiguos egipcios que su aparición al amanecer marcaba la inundación del Nilo.' },
  { emoji: '🪐', texto: 'Venus gira en dirección contraria al resto de los planetas (excepto Urano). Un día en Venus dura más que su año.' },
  { emoji: '💎', texto: 'En el centro de la galaxia existe un agujero negro supermasivo llamado Sagitario A*, con una masa equivalente a 4 millones de soles.' },
  { emoji: '🌊', texto: 'Durante la luna llena y la luna nueva, las mareas son más extremas. Se llaman "mareas vivas" y ocurren cuando el Sol, la Luna y la Tierra se alinean.' },
  { emoji: '☀️', texto: 'El Sol tardará otros 5.000 millones de años en convertirse en gigante roja. Cuando lo haga, se expandirá hasta engullir a Mercurio, Venus y posiblemente la Tierra.' },
  { emoji: '🌙', texto: 'El calendario chino y el hebreo son lunisolares: combinan el ciclo lunar con el solar para mantener las estaciones. Son los más precisos para la vida agrícola.' },
  { emoji: '🔭', texto: 'La sonda Voyager 1, lanzada en 1977, es el objeto humano más alejado. Viaja a 61.000 km/h y sigue funcionando con energía nuclear.' },
  { emoji: '💫', texto: 'Las auroras boreales son causadas por partículas cargadas del Sol que chocan con la atmósfera. La luna llena puede hacer que sean menos visibles al iluminar el cielo.' },
  { emoji: '🌌', texto: 'Las galaxias espirales como la Vía Láctea tienen brazos que no rotan como un sólido rígido. Cada estrella orbita independientemente, y los brazos son ondas de densidad.' },
  { emoji: '🌙', texto: 'En la antigua Roma, el calendario original tenía 10 meses y comenzaba en marzo (Marte). Enero y febrero fueron agregados después, disrumpiendo el conteo original.' },
  { emoji: '🔴', texto: 'El polo norte magnético de la Tierra se mueve. En los últimos 150 años se ha desplazado más de 1.000 km hacia Siberia, acelerándose en las últimas décadas.' },
  { emoji: '⭐', texto: 'Las estrellas binarias son más comunes que las solitarias como el Sol. Se estima que el 50% de las estrellas de la Vía Láctea tienen al menos una compañera.' },
  { emoji: '🌕', texto: 'La Luna tiene una "cara oscura permanente" en términos de temperatura: la cara oculta puede llegar a -173°C en la noche, mientras el lado visible varía más.' },
  { emoji: '🪐', texto: 'Urano orbita el Sol prácticamente "de lado", con una inclinación de 98°. Se cree que fue golpeado por un objeto gigante en el pasado remoto.' },
  { emoji: '✨', texto: 'Los pulsares son estrellas de neutrones que emiten haces de radiación tan precisos que se usaron como relojes naturales para detectar ondas gravitacionales.' },
  { emoji: '🌙', texto: 'La palabra "mes" en muchos idiomas deriva de "luna": month (inglés), mois (francés), mes (español), todos vienen del proto-indoeuropeo "méh₁nōts".' },
  { emoji: '☿', texto: 'Mercurio retrogrado es un fenómeno óptico real: el planeta parece moverse hacia atrás desde la perspectiva terrestre cuando lo superamos en nuestra órbita.' },
  { emoji: '💫', texto: 'Las ondas gravitacionales, predichas por Einstein en 1916, fueron detectadas por primera vez en 2015. Viajan a la velocidad de la luz y distorsionan el espacio-tiempo.' },
  { emoji: '🌟', texto: 'Existe una estrella llamada KIC 8462852 (Tabby\'s Star) que se atenúa de formas inexplicables. Es uno de los mayores misterios astronómicos actuales.' },
  { emoji: '🌙', texto: 'El efecto gravitacional de la Luna sobre el cuerpo humano es miles de veces menor que el de un mosquito posado sobre tu brazo.' },
  { emoji: '🔭', texto: 'El telescopio James Webb puede ver galaxias formadas apenas 300 millones de años después del Big Bang, casi el límite observable del universo.' },
  { emoji: '🌌', texto: 'La energía oscura representa el 68% del universo y está causando que la expansión cósmica se acelere. No sabemos qué es.' },
  { emoji: '⭐', texto: 'Cuando una estrella masiva explota en supernova, libera más energía en segundos que el Sol en su vida completa de 10.000 millones de años.' },
  { emoji: '🪐', texto: 'Europa, la luna de Júpiter, tiene un océano de agua líquida bajo su corteza de hielo con más agua que todos los océanos de la Tierra juntos.' },
  { emoji: '🌙', texto: 'Los calendarios islámicos son puramente lunares, por eso el Ramadán se desplaza a lo largo del año gregoriano, rotando por todas las estaciones en 33 años.' },
  { emoji: '💎', texto: 'La temperatura en el núcleo del Sol es de 15 millones de grados Celsius. La superficie "solo" llega a 5.500°C — más fresca que el núcleo.' },
  { emoji: '🌕', texto: 'La Luna tiene cráteres con agua helada en sus polos que nunca han recibido luz solar en miles de millones de años. Es un fósil del sistema solar primitivo.' },

  // MARZO
  { emoji: '🌸', texto: 'El equinoccio de otoño o primavera ocurre cuando la duración del día y la noche son casi iguales en todo el planeta. No es exactamente igual por la refracción atmosférica.' },
  { emoji: '🌙', texto: 'La primera persona en calcular la circunferencia de la Tierra fue Eratóstenes en el siglo III a.C., con una precisión asombrosa usando solo una vara y sombras.' },
  { emoji: '⭐', texto: 'Las estrellas no parpadean. Lo que vemos como parpadeo es causado por la turbulencia atmosférica terrestre. En el espacio, las estrellas brillan de forma constante.' },
  { emoji: '🔴', texto: 'El agua en Marte existió hace 3.800 millones de años. Los valles y cauces visibles en su superficie son cicatrices de ríos y océanos extintos.' },
  { emoji: '💫', texto: 'La velocidad de escape de la Tierra es 11.2 km/s. Cualquier objeto que no alcance esa velocidad regresará atraído por la gravedad terrestre.' },
  { emoji: '🌌', texto: 'La Vía Láctea tiene entre 100.000 y 400.000 millones de estrellas. El número exacto es imposible de determinar porque no podemos ver toda la galaxia.' },
  { emoji: '🪐', texto: 'Los vientos en Neptuno alcanzan 2.100 km/h, los más rápidos del sistema solar. Más rápidos que cualquier viento registrado en la Tierra.' },
  { emoji: '🌙', texto: 'Ptolomeo, en el siglo II, creyó que la Luna influía en los humores del cuerpo. La medicina humoral que dominó 1500 años incluyó los ciclos lunares como factor.' },
  { emoji: '☀️', texto: 'La luz tarda 8 minutos y 20 segundos en llegar del Sol a la Tierra. Si el Sol desapareciera, seguiríamos viéndolo durante esos minutos.' },
  { emoji: '✨', texto: 'Los quásares son los objetos más brillantes del universo. Son núcleos de galaxias con agujeros negros supermasivos activos que emiten más luz que mil galaxias.' },
  { emoji: '🌕', texto: 'La gravedad en la Luna es 1/6 de la terrestre. Un objeto que pesa 60 kg en la Tierra pesaría apenas 10 kg en la Luna.' },
  { emoji: '🔭', texto: 'Hubble demostró en 1929 que el universo se está expandiendo al observar que las galaxias se alejan de nosotros. Cuanto más lejos están, más rápido se alejan.' },
  { emoji: '💎', texto: 'Hay un planeta de diamante: 55 Cancri e tiene una masa 8 veces la Tierra y un tercio de su composición podría ser carbono en forma de diamante.' },
  { emoji: '🌙', texto: 'Las fases de la Luna visibles desde el hemisferio sur son "al revés" respecto al norte. Lo que parece una C en el norte, es una D en el sur.' },
  { emoji: '⭐', texto: 'La constelación de Orión no existe como tal: sus estrellas están a distancias completamente distintas de la Tierra y solo parecen agrupadas por perspectiva.' },
  { emoji: '🌟', texto: 'El universo es plano — no curvo — con una precisión del 0.4%. Esto significa que la geometría euclidiana funciona a escalas cósmicas.' },
  { emoji: '🌙', texto: 'La influencia de la Luna en los seres vivos más estudiada es en los corales: se reproducen en masa sincronizados con las fases lunares.' },
  { emoji: '🪐', texto: 'Titán, la luna más grande de Saturno, tiene ríos y lagos de metano líquido. Es el único objeto del sistema solar además de la Tierra con líquidos en su superficie.' },
  { emoji: '💫', texto: 'Los agujeros negros de masa estelar se forman cuando estrellas masivas (más de 20 veces el Sol) colapsan al fin de su vida.' },
  { emoji: '🌌', texto: 'La Gran Nube de Magallanes, una galaxia satélite de la Vía Láctea, es visible a simple vista desde el hemisferio sur. Está a 160.000 años luz.' },
  { emoji: '☿', texto: 'A pesar de ser el planeta más cercano al Sol, Mercurio no es el más caliente. Venus lo supera por su efecto invernadero extremo: 465°C promedio.' },
  { emoji: '🌙', texto: 'El ciclo de Metón (19 años) es el período en que las fases lunares vuelven a caer en los mismos días del año. Fue descubierto en el siglo V a.C.' },
  { emoji: '🔴', texto: 'El suelo de Marte contiene compuestos de hierro oxidado, por eso es rojo. La misma razón por la que la sangre y el óxido son rojos.' },
  { emoji: '⭐', texto: 'La nebulosa de la Hélice, llamada "el ojo de Dios", es una nebulosa planetaria: los restos de una estrella como el Sol al final de su vida.' },
  { emoji: '🌕', texto: 'La Luna no tiene color propio: es gris. Parece blanca porque contrasta con el cielo oscuro. En el horizonte puede verse naranja o roja por la refracción.' },
  { emoji: '💎', texto: 'Las estrellas de carbono son raras: son gigantes rojas en las que el carbono domina la atmósfera, dándoles un color naranja-rojizo intensísimo.' },
  { emoji: '🌙', texto: 'En Mesopotamia, los astrólogos babilónicos documentaron eclipses lunares durante siglos. Sus tablas astronómicas son precursoras directas de la astronomía moderna.' },
  { emoji: '✨', texto: 'La fuerza nuclear fuerte es la más poderosa de las cuatro fuerzas fundamentales. Sin ella, los protones del núcleo atómico se repelerían y los átomos no existirían.' },
  { emoji: '🌟', texto: 'El punto más frío del sistema solar no está en los planetas exteriores: es la Nube de Boomerang, a apenas 1 grado sobre el cero absoluto.' },
  { emoji: '🌙', texto: 'El nombre de los días de la semana en muchos idiomas deriva de los planetas: Sunday (Sol), Monday (Luna), Saturday (Saturno), y los demás de dioses asociados a planetas.' },
  { emoji: '🪐', texto: 'Encélado, luna de Saturno, tiene géiseres de vapor de agua que salen de su polo sur. Bajo su hielo hay un océano que podría albergar vida.' },

  // ABRIL
  { emoji: '🌱', texto: 'La astrología helenística nació de la fusión de la astronomía babilónica con la filosofía griega alrededor del siglo III a.C. en Alejandría, Egipto.' },
  { emoji: '💫', texto: 'La luz visible representa solo una pequeña fracción del espectro electromagnético. Los telescopios modernos pueden ver en radio, infrarrojo, ultravioleta, rayos X y gamma.' },
  { emoji: '🌙', texto: 'Los nativos americanos Ojibwe tienen 13 lunas en su calendario, cada una con nombre que describe la naturaleza del mes: Luna del Esturgeon, Luna de la Cosecha, etc.' },
  { emoji: '⭐', texto: 'El Sol es una estrella de tipo espectral G2V, clasificada como "enana amarilla". Esta clase representa solo el 7% de las estrellas de la Vía Láctea.' },
  { emoji: '🔭', texto: 'El primer telescopio fue inventado por Hans Lippershey en 1608. Un año después, Galileo lo apuntó al cielo y cambió para siempre nuestra visión del universo.' },
  { emoji: '🌌', texto: 'Las galaxias elípticas son las más antiguas del universo. Han "quemado" todo su gas y ya no forman nuevas estrellas. Son cementerios estelares.' },
  { emoji: '🔴', texto: 'En Marte, un año dura 687 días terrestres. Las estaciones marcianas son similares a las nuestras, pero duran el doble.' },
  { emoji: '🌙', texto: 'La Luna se formó hace 4.500 millones de años cuando un objeto del tamaño de Marte (llamado Theia) chocó con la Tierra primitiva y el material eyectado se condensó.' },
  { emoji: '☀️', texto: 'El Sol convierte 4 millones de toneladas de masa en energía cada segundo a través de la fusión nuclear. Ha estado haciendo esto durante 4.600 millones de años.' },
  { emoji: '💎', texto: 'PSR J0437-4715 es un púlsar que completa 174 rotaciones por segundo, tan preciso que se usa como reloj atómico natural para calibrar instrumentos científicos.' },
  { emoji: '🌙', texto: 'Los chimpancés, orangutanes y otros primates muestran cambios de comportamiento en luna llena, posiblemente relacionados con el aumento de luminosidad nocturna.' },
  { emoji: '🪐', texto: 'Jupiter tiene 95 lunas conocidas, más que cualquier otro planeta. Las cuatro más grandes (Io, Europa, Ganímedes y Calisto) fueron las primeras en descubrirse.' },
  { emoji: '✨', texto: 'La nebulosa de Orión, visible a simple vista en el cinturón de Orión, es una fábrica de estrellas activa. Tiene 700 estrellas jóvenes en formación.' },
  { emoji: '🌟', texto: 'Ganímedes, luna de Júpiter, es más grande que Mercurio. Es el satélite natural más grande del sistema solar y tiene su propio campo magnético.' },
  { emoji: '🌙', texto: 'El agua de los océanos de la Tierra podría haber llegado en parte de cometas y asteroides durante el período llamado "Gran Bombardeo Tardío" hace 4.000 millones de años.' },
  { emoji: '🔴', texto: 'Los cráteres de impacto en la Luna son un registro fósil de los bombardeos que sufrió el sistema solar en sus primeros tiempos. En la Tierra, la erosión los borra.' },
  { emoji: '💫', texto: 'El principio de incertidumbre de Heisenberg dice que no podemos conocer simultáneamente la posición y el momento exacto de una partícula. El universo es fundamentalmente incierto.' },
  { emoji: '🌌', texto: 'La Gran Pared de Sloan es la estructura más grande conocida del universo: una red de galaxias que se extiende 1.380 millones de años luz.' },
  { emoji: '⭐', texto: 'Las enanas marrones son objetos entre planetas y estrellas: demasiado grandes para ser planetas, demasiado pequeños para encender la fusión nuclear. Son "estrellas fallidas".' },
  { emoji: '🌙', texto: 'Las mareas en el Mediterráneo son casi inexistentes porque el mar es prácticamente cerrado y tiene poca masa de agua para que la Luna las amplifique.' },
  { emoji: '🪐', texto: 'El sistema de anillos de Saturno se formó hace relativamente poco tiempo en escala cósmica: entre 10 y 100 millones de años. Los dinosaurios ya existían.' },
  { emoji: '☀️', texto: 'Las manchas solares son regiones magnéticas más frías en la superficie del Sol. Siguen un ciclo de 11 años de actividad que afecta las comunicaciones en la Tierra.' },
  { emoji: '🌙', texto: 'La superstición de que la Luna llena aumenta los crímenes o las visitas a emergencias ha sido estudiada científicamente muchas veces. No hay evidencia estadística que la apoye.' },
  { emoji: '💎', texto: 'El elemento hierro en tu sangre fue forjado en el núcleo de una estrella masiva que murió antes que el Sol naciera. Literalmente somos polvo de estrellas.' },
  { emoji: '🔭', texto: 'El radiotelescopio FAST en China tiene 500 metros de diámetro y es el más grande del mundo. Puede detectar señales de civilizaciones alienígenas a miles de años luz.' },
  { emoji: '🌟', texto: 'UY Scuti es una de las estrellas más grandes conocidas: si estuviera en el centro del sistema solar, engulliría todo hasta más allá de Júpiter.' },
  { emoji: '🌙', texto: 'El Ramadán islámico comienza con la visión de la Luna creciente a simple vista. Esta práctica conecta a más de 1.800 millones de personas con el cosmos mensualmente.' },
  { emoji: '✨', texto: 'Las estrellas de tipo O son las más masivas, calientes y brillantes, pero viven apenas millones de años. El Sol, una estrella G, vive 10.000 millones de años.' },
  { emoji: '🌌', texto: 'El universo tiene aproximadamente 2 billones de galaxias en la parte observable. Solo la Vía Láctea tiene entre 100 y 400 mil millones de estrellas.' },
  { emoji: '🌙', texto: 'Las mareas lunares frenaron lentamente la rotación de la Tierra. Hace 500 millones de años, un día terrestre duraba solo 22 horas.' },

  // MAYO
  { emoji: '🌺', texto: 'La NASA tiene un programa llamado "Lunar Reconnaissance Orbiter" que mapea la Luna en alta resolución. Sus imágenes revelaron hielo en cráteres polares permanentemente en sombra.' },
  { emoji: '⭐', texto: 'La constelación de la Cruz del Sur es tan importante en el hemisferio sur que aparece en las banderas de Australia, Nueva Zelanda, Brasil, Papua Nueva Guinea y Samoa.' },
  { emoji: '💫', texto: 'El universo se expande más rápido de lo que debería según nuestros modelos. Esta discrepancia se llama "tensión de Hubble" y es uno de los grandes misterios actuales.' },
  { emoji: '🌙', texto: 'Los aztecas temían los eclipses solares: creían que el Sol moría y hacían sacrificios para que renaciera. Los eclipses lunares también tenían interpretaciones rituales.' },
  { emoji: '🔴', texto: 'Io, luna de Júpiter, tiene más de 400 volcanes activos. Es el objeto geológicamente más activo del sistema solar, con erupciones de azufre visibles desde la Tierra.' },
  { emoji: '🌌', texto: 'Los filamentos cósmicos son las estructuras más grandes del universo: redes de gas y galaxias que forman la "telaraña cósmica". Los vacíos entre ellos son casi perfectos.' },
  { emoji: '🌟', texto: 'Existen planetas errantes — planetas sin estrella — flotando solos en el espacio interestelar. Se estiman miles de millones solo en la Vía Láctea.' },
  { emoji: '🌙', texto: 'El observatorio de Stonehenge en Inglaterra estaba alineado con los solsticios y posiblemente con los ciclos lunares. Data de hace 5.000 años.' },
  { emoji: '☀️', texto: 'Las tormentas solares pueden afectar las redes eléctricas de la Tierra. La Tormenta de Carrington de 1859 habría destruido los sistemas eléctricos modernos si ocurriera hoy.' },
  { emoji: '🪐', texto: 'El tiempo en Júpiter es tan extremo que tiene tormentas de amoníaco. Las nubes rojas son complejos compuestos químicos formados a presiones inimaginables.' },
  { emoji: '💎', texto: 'La materia visible (estrellas, planetas, gas) es solo el 5% del universo. El resto es materia oscura (27%) y energía oscura (68%), ambas completamente misteriosas.' },
  { emoji: '🌙', texto: 'En la China antigua, los eclipses lunares eran interpretados como un dragón que devoraba la Luna. Los tambores y el ruido servían para ahuyentarlo.' },
  { emoji: '🔭', texto: 'El Hubble Space Telescope ha tomado más de 1.5 millones de observaciones desde 1990. Su imagen más famosa, el "Campo Profundo", muestra 10.000 galaxias.' },
  { emoji: '✨', texto: 'Los neutrinos son partículas subatómicas tan ligeras y esquivas que billones pasan a través de tu cuerpo cada segundo sin interactuar con nada.' },
  { emoji: '🌙', texto: 'La gravedad de la Luna causa que la Tierra tenga una ligera "joroba" en el lado que enfrenta a la Luna y otro en el lado opuesto — por eso hay dos pleamares por día.' },
  { emoji: '⭐', texto: 'Proxima b es un exoplaneta en la zona habitable de Próxima Centauri, la estrella más cercana al Sol. Podría tener condiciones para el agua líquida.' },
  { emoji: '🌌', texto: 'El Big Bang no fue una explosión en el espacio: fue una expansión del espacio mismo. No hay un centro del universo; cada punto se aleja de los demás.' },
  { emoji: '🌙', texto: 'Los mayas desarrollaron un calendario lunar extremadamente preciso. Su ciclo de 405 lunas (33.7 años) tenía un error de solo 34 segundos por año.' },
  { emoji: '💫', texto: 'El efecto Doppler en la luz nos permite saber si una estrella se acerca o aleja: la luz azulada indica acercamiento y la rojiza, alejamiento.' },
  { emoji: '🔴', texto: 'La atmósfera de Venus es 90 veces más densa que la Tierra. La presión en su superficie es equivalente a estar a 900 metros bajo el mar.' },
  { emoji: '🌟', texto: 'Las estrellas de Wolf-Rayet son las más masivas y calientes conocidas. Expulsan sus capas externas en vientos estelares tan intensos que son visibles.' },
  { emoji: '🌙', texto: 'El Talmud menciona que la Luna gobierna el agua y los fluidos. Esta idea conecta con la observación real de las mareas, aunque la fisiología humana no se rige igual.' },
  { emoji: '🪐', texto: 'Miranda, luna de Urano, tiene el acantilado más alto del sistema solar: Verona Rupes, de 20 km de altura. Caer desde allí tomaría 12 minutos.' },
  { emoji: '☀️', texto: 'El interior del Sol está tan comprimido que un fotón de luz puede tardar 100.000 años en escapar desde el núcleo hasta la superficie, aunque luego llega a la Tierra en 8 minutos.' },
  { emoji: '💎', texto: 'Hay una estrella enana blanca llamada BPM 37093 (Lucy) cuyo núcleo es esencialmente un cristal de carbono de 10²⁹ quilates. Un diamante del tamaño de la Luna.' },
  { emoji: '🌙', texto: 'El término "menstrual" proviene del latín "mensis" (mes) y del griego "mene" (Luna), evidenciando la antigua asociación entre el ciclo femenino y el lunar.' },
  { emoji: '🔭', texto: 'TESS (Transiting Exoplanet Survey Satellite) ha descubierto más de 5.000 planetas fuera del sistema solar monitoreando el parpadeo de las estrellas.' },
  { emoji: '✨', texto: 'La temperatura del espacio interestelar es de aproximadamente -270°C, apenas 3 grados sobre el cero absoluto. Esta temperatura es el "eco" del Big Bang.' },
  { emoji: '🌌', texto: 'El universo local se mueve hacia una concentración masiva de materia llamada el "Gran Atractor", una región a 250 millones de años luz con la masa de decenas de miles de galaxias.' },
  { emoji: '🌙', texto: 'Los vikingos tenían nombres para la Luna según sus fases. La "Luna de nieve" marcaba el inicio del invierno y la "Luna de sangre" señalaba la temporada de caza.' },
  { emoji: '⭐', texto: 'El año luz es la distancia que recorre la luz en un año: 9.461 mil millones de kilómetros. La estrella más cercana está a 4.24 años luz.' },

  // JUNIO-DICIEMBRE (completando hasta 365)
  { emoji: '🌙', texto: 'El ciclo lunar completo de 29.53 días se llama "mes sinódico". Es la base de la mayoría de los calendarios lunares en la historia humana.' },
  { emoji: '☀️', texto: 'El solsticio de junio marca el día más largo en el hemisferio norte y el más corto en el sur. La Tierra no está más cerca del Sol en verano: es la inclinación axial.' },
  { emoji: '💫', texto: 'El agujero negro más masivo conocido, TON 618, tiene una masa de 66.000 millones de soles. Si estuviera donde el Sol, engulliría el sistema solar.' },
  { emoji: '🌙', texto: 'La "Luna azul" no es azul: es el nombre que se da a la segunda luna llena en un mismo mes calendario. Ocurre cada 2-3 años.' },
  { emoji: '⭐', texto: 'El telescopio espacial Kepler descubrió que hay más planetas que estrellas en la Vía Láctea. Casi cada estrella tiene al menos un planeta.' },
  { emoji: '🪐', texto: 'Los anillos de Júpiter existen pero son invisibles a simple vista: están compuestos de polvo oscuro en lugar de hielo brillante como los de Saturno.' },
  { emoji: '🌟', texto: 'La astrología y la astronomía fueron la misma disciplina durante milenios. Se separaron gradualmente entre los siglos XVII y XVIII con la revolución científica.' },
  { emoji: '🌙', texto: 'La "Superluna" ocurre cuando la luna llena coincide con el perigeo (punto más cercano a la Tierra). Puede verse hasta un 14% más grande y 30% más brillante.' },
  { emoji: '💎', texto: 'El planeta Kepler-22b orbita en la zona habitable de su estrella y podría tener agua líquida. Está a 620 años luz de la Tierra.' },
  { emoji: '🌌', texto: 'En el futuro lejano, dentro de 100 billones de años, las últimas estrellas se apagarán y el universo entrará en la "Era Degenerada" dominada por enanas negras.' },
  { emoji: '🌙', texto: 'La "Luna de cosecha" es la luna llena más cercana al equinoccio de otoño. Históricamente, su luz extra permitía a los agricultores cosechar hasta tarde.' },
  { emoji: '🔴', texto: 'El cañón Valles Marineris en Marte tiene 4.000 km de largo y 7 km de profundidad. El Gran Cañón del Colorado cabe dentro de uno de sus tributarios.' },
  { emoji: '✨', texto: 'Los rayos cósmicos son partículas subatómicas que viajan casi a la velocidad de la luz y llegan continuamente a la Tierra desde el universo profundo.' },
  { emoji: '🌙', texto: 'En la mitología griega, Selene era la diosa de la Luna que conducía un carro plateado por el cielo nocturno. Artemisa, hermana de Apolo, también era asociada a la Luna.' },
  { emoji: '🌟', texto: 'La bioluminiscencia marina sincronizada con las fases lunares es documentada en varias especies, especialmente gusanos y peces, que se reproducen en fechas lunares específicas.' },
  { emoji: '🪐', texto: 'Caronte, la luna de Plutón, es tan grande en relación a Plutón que ambos orbitan un punto en el espacio entre ellos. Son considerados un sistema binario enano.' },
  { emoji: '💫', texto: 'La presión en el centro de Júpiter es tan alta que el hidrógeno se convierte en un metal líquido conductor de electricidad. No existe nada así en la Tierra.' },
  { emoji: '🌙', texto: 'La Luna es el quinto satélite natural más grande del sistema solar, pero en relación al tamaño de su planeta es la luna más grande en proporción.' },
  { emoji: '☀️', texto: 'El campo magnético de la Tierra nos protege del viento solar. Sin él, el Sol habría despojado a la Tierra de su atmósfera hace miles de millones de años, como le pasó a Marte.' },
  { emoji: '⭐', texto: 'Las estrellas de población III son las primeras estrellas del universo, formadas solo de hidrógeno y helio. Nunca las hemos observado pero el James Webb podría hacerlo.' },
  { emoji: '🌌', texto: 'El universo observable tiene 93.000 millones de años luz de diámetro, aunque solo tiene 13.800 millones de años. La expansión del espacio lo hace posible.' },
  { emoji: '🌙', texto: 'La "Luna de sangre" es una luna llena durante un eclipse lunar total. La Luna toma color rojo porque la luz del Sol se refracta en la atmósfera terrestre.' },
  { emoji: '💎', texto: 'La estrella WISE 0855-0714 tiene una temperatura de -13°C, más fría que la Tierra. Es el objeto más frío fuera del sistema solar jamás observado.' },
  { emoji: '🔭', texto: 'Las primeras observaciones de Júpiter por la sonda Juno revelaron que sus tormentas son mucho más profundas de lo esperado: hasta 3.000 km hacia el interior.' },
  { emoji: '🌙', texto: 'En el Islam, la Luna creciente y la estrella son símbolo del calendario lunar que guía la vida religiosa. El símbolo fue adoptado del Imperio Otomano.' },
  { emoji: '✨', texto: 'Los planetas del sistema solar se formaron hace 4.600 millones de años a partir de la misma nube de gas y polvo que el Sol. Somos literalmente familia.' },
  { emoji: '🌟', texto: 'La zona de habitabilidad de una estrella, donde el agua puede existir líquida, varía según el tipo de estrella. Las enanas rojas tienen zonas muy cercanas.' },
  { emoji: '🌙', texto: 'Los biológos marinos registran que las tortugas marinas emergen a desovar sincronizadas con la luna llena. La luz lunar guía a las crías hacia el mar.' },
  { emoji: '🪐', texto: 'Neptuno fue el primer planeta descubierto por predicción matemática, no por observación directa. Le Verrier calculó su posición por las perturbaciones en la órbita de Urano.' },
  { emoji: '💫', texto: 'La energía de fusión nuclear que el Sol produce viene de convertir hidrógeno en helio. En el proceso, el Sol pierde 4.000 kg de masa por segundo, transformada en energía.' },
  { emoji: '🌙', texto: 'La práctica de "bañar cristales en la luna" tiene bases en la tradición pero ninguna física. Sin embargo, el ritual de intención es un poderoso acto psicológico de programación.' },
  { emoji: '🔴', texto: 'La sonda Mars Perseverance ha producido oxígeno en Marte por electrólisis del CO₂ atmosférico. Es el primer paso hacia la respiración humana en otro planeta.' },
  { emoji: '⭐', texto: 'La Via Láctea tiene un halo estelar que se extiende 300.000 años luz. La mayor parte de sus estrellas están en el disco plano, pero el halo contiene las más antiguas.' },
  { emoji: '🌌', texto: 'En el futuro, Andrómeda y la Vía Láctea se fusionarán pero casi ninguna estrella chocará con otra: el espacio entre ellas es demasiado grande.' },
  { emoji: '🌙', texto: 'El "efecto halo" de la Luna es causado por cristales de hielo en la atmósfera. El halo de 22 grados alrededor de la Luna era interpretado como presagio en muchas culturas.' },
  { emoji: '💎', texto: 'Los meteoritos de hierro-níquel son los fragmentos del núcleo de planetesimales destruidos. Cuando los tenés en la mano, tocás el corazón de un mundo que ya no existe.' },
  { emoji: '✨', texto: 'Las reacciones nucleares en el Sol producen neutrinos que escapan inmediatamente. Los detectamos en detectores bajo tierra que nos dan información del interior solar en tiempo real.' },
  { emoji: '🌟', texto: 'La constante de Hubble mide la tasa de expansión del universo. Dos métodos diferentes de medirla dan resultados distintos — el misterio de la "tensión de Hubble" sigue sin resolver.' },
  { emoji: '🌙', texto: 'La cultura celta dividía el año en cuartos lunares. Sus festivales — Imbolc, Beltane, Lughnasadh y Samhain — caían en los puntos medios entre solsticios y equinoccios.' },
  { emoji: '🔭', texto: 'El interferómetro LIGO detectó las primeras ondas gravitacionales en 2015, confirmando la predicción de Einstein de 1916. Las ondas venían de dos agujeros negros que se fusionaron.' },
  { emoji: '🌙', texto: 'Hipócrates, el padre de la medicina, creía que la Luna influía en el cuerpo humano. Sus textos mencionan que las crisis de las enfermedades ocurrían en fases lunares específicas.' },
  { emoji: '🪐', texto: 'El sistema de Trappist-1 tiene 7 planetas del tamaño de la Tierra, 3 en zona habitable. Está a 40 años luz y es el sistema planetario más prometedor para vida conocido.' },
  { emoji: '💫', texto: 'Las púlsares de milisegundo giran cientos de veces por segundo y son tan estables que pueden usarse como relojes más precisos que los atómicos.' },
  { emoji: '🌙', texto: 'La Luna tiene una magnetosfera extremadamente débil, vestigio del pasado cuando tenía un núcleo activo. Los astronautas encontraron rocas lunares ligeramente magnetizadas.' },
  { emoji: '☀️', texto: 'El Sol está en el brazo de Orión de la Vía Láctea, a 26.000 años luz del centro galáctico. Completa una órbita completa alrededor del centro en 225 millones de años.' },
  { emoji: '🌌', texto: 'La primera imagen de un agujero negro se publicó en 2019: Messier 87*, a 55 millones de años luz. Fue posible gracias al Event Horizon Telescope, una red de observatorios globales.' },
  { emoji: '🌙', texto: 'En japonés, "tsukimi" es la tradición de contemplar la luna llena en otoño. Se celebra desde el siglo X con ofrendas de arroz y hierbas de temporada.' },
  { emoji: '⭐', texto: 'La fusión de dos estrellas de neutrones produce un "kilonova" que crea en segundos elementos más pesados que el hierro, incluyendo todo el oro y platino del universo.' },
  { emoji: '🌟', texto: 'El problema de la constante cosmológica es uno de los grandes misterios de la física: la energía del vacío cuántico es 10¹²⁰ veces mayor de lo que observamos en el universo.' },
  { emoji: '🌙', texto: 'En la tradición wicca, las 13 lunas llenas del año tienen cada una un nombre y propósito ritual específico, desde la "Luna de las Tormentas" en febrero hasta la "Luna Fría" en diciembre.' },
  { emoji: '💎', texto: 'La velocidad de la luz es un límite absoluto del universo. No se puede superar, no porque no tengamos tecnología, sino porque la física lo prohíbe.' },
  { emoji: '🔴', texto: 'El agua en Europa (luna de Júpiter) es salada y contiene compuestos orgánicos. Las condiciones de su océano subsuperficial son similares a las de los océanos terrestres profundos.' },
  { emoji: '🌙', texto: 'La energía emocional que sentimos en luna llena puede explicarse parcialmente: la mayor luminosidad nocturna históricamente interrumpía el sueño, generando estados alterados.' },
  { emoji: '🪐', texto: 'La superficie de Venus está cubierta de volcanes. La sonda Magellan mapeó el 98% de su superficie con radar y reveló miles de estructuras volcánicas.' },
  { emoji: '✨', texto: 'El plano ecuatorial de la Tierra está inclinado 23.5° respecto a su órbita. Esta inclinación es responsable de las estaciones y fue clave para el desarrollo de la vida.' },
  { emoji: '🌌', texto: 'Hay un misterioso "plano de evitación" en el mapa de galaxias: una región donde casi no vemos galaxias. No es un vacío real: es la Vía Láctea bloqueando nuestra vista.' },
  { emoji: '🌙', texto: 'El símbolo astrológico de la Luna ☽ representa la luna creciente y es uno de los símbolos más antiguos de la humanidad, encontrado en tablillas cuneiformes de 3.000 a.C.' },
  { emoji: '💫', texto: 'Las galaxias irregulares, como las Nubes de Magallanes, han sido distorsionadas por interacciones gravitacionales con galaxias más grandes, perdiendo su forma original.' },
  { emoji: '🌟', texto: 'El sol tiene manchas oscuras (manchas solares) que siguen un ciclo de 11 años. En el máximo solar, hay más auroras, tormentas electromagnéticas y riesgo para satélites.' },
  { emoji: '🌙', texto: 'La palabra "selenio", el elemento químico del número 34, viene de Selene, la diosa griega de la Luna, porque su brillo recordaba el de la plata lunar.' },
  { emoji: '🔭', texto: 'La misión Artemis planea llevar humanos de nuevo a la Luna en 2026, incluyendo la primera mujer y la primera persona de color en pisar suelo lunar.' },
  { emoji: '⭐', texto: 'Las estrellas de carbono son raras joyas del universo: gigantes rojas que han "mezclado" carbono de su interior a la superficie, brillando en tonos anaranjados profundos.' },
  { emoji: '🌙', texto: 'La "luna de miel" tiene origen en la tradición de beber hidromiel durante un ciclo lunar completo después de la boda, para asegurar fertilidad y dulzura al matrimonio.' },
  { emoji: '🌌', texto: 'La mayor parte de los átomos del cuerpo humano fueron creados en estrellas. El hidrógeno viene del Big Bang, el resto fue forjado en núcleos estelares.' },
  { emoji: '💎', texto: 'La heliosfera, la burbuja de viento solar que protege al sistema solar de la radiación cósmica, se extiende hasta 18.000 millones de km. La Voyager 1 la cruzó en 2012.' },
  { emoji: '🌙', texto: 'En la tradición budista tibetana, la luna llena y la luna nueva son días de especial poder espiritual. Las ceremonias y meditaciones más importantes se celebran en esas fechas.' },
]

/**
 * Obtiene el dato curioso del día basado en el día del año
 * Rota automáticamente sin repetir hasta completar el ciclo
 */
export function getDatoCuriosoDelDia(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 0)
  const diff = date - start
  const oneDay = 1000 * 60 * 60 * 24
  const dayOfYear = Math.floor(diff / oneDay)
  const index = (dayOfYear - 1) % DATOS_CURIOSOS.length
  return DATOS_CURIOSOS[Math.max(0, index)]
}
