// Los 78 arcanos del Tarot Rider-Waite en español
// Incluye arcanos mayores (0-21) y menores (22-77)

export const TAROT_CARDS = [
  // ═══════════════════════════════
  // ARCANOS MAYORES (0-21)
  // ═══════════════════════════════
  {
    index: 0,
    nombre: 'El Loco',
    numeral: '0',
    emoji: '🌟',
    arcano: 'mayor',
    palabrasClave: ['Libertad', 'Aventura', 'Espontaneidad', 'Inocencia', 'Nuevo comienzo'],
    descripcion: 'El Loco representa el alma en su estado más puro, lista para saltar al vacío con confianza ciega. Es el viaje antes de que comience, la posibilidad antes de la forma.',
    mensaje: 'Hoy el universo te invita a soltar el control y confiar en el salto. Lo que parece un vacío puede ser el inicio de tu mayor aventura. Dejá que la vida te sorprenda.',
  },
  {
    index: 1,
    nombre: 'El Mago',
    numeral: 'I',
    emoji: '🪄',
    arcano: 'mayor',
    palabrasClave: ['Voluntad', 'Poder', 'Manifestación', 'Habilidad', 'Acción'],
    descripcion: 'El Mago tiene a su disposición todas las herramientas del universo. Representa la capacidad de transformar la intención en realidad concreta.',
    mensaje: 'Tenés todo lo que necesitás. Hoy es día de actuar, no de esperar. Tus herramientas están frente a vos — usálas con intención y confianza.',
  },
  {
    index: 2,
    nombre: 'La Sacerdotisa',
    numeral: 'II',
    emoji: '🔮',
    arcano: 'mayor',
    palabrasClave: ['Intuición', 'Misterio', 'Sabiduría interior', 'Silencio', 'Conocimiento'],
    descripcion: 'La Sacerdotisa guarda los secretos entre los mundos. Representa el conocimiento que no se aprende sino que se siente, la sabiduría que habita en el silencio.',
    mensaje: 'Tu intuición habla más fuerte que cualquier lógica hoy. Callá el ruido exterior y escuchá esa voz suave que ya sabe la respuesta. Confiá en lo que sentís.',
  },
  {
    index: 3,
    nombre: 'La Emperatriz',
    numeral: 'III',
    emoji: '🌸',
    arcano: 'mayor',
    palabrasClave: ['Abundancia', 'Fertilidad', 'Naturaleza', 'Creatividad', 'Nutrición'],
    descripcion: 'La Emperatriz es la madre de todo lo que existe. Representa la creatividad en su forma más generosa, la abundancia que florece cuando nos conectamos con la tierra.',
    mensaje: 'Hoy es día de nutrir y de recibir. Permitite florecer, crear, amar con generosidad. La abundancia que buscás ya está creciendo dentro tuyo.',
  },
  {
    index: 4,
    nombre: 'El Emperador',
    numeral: 'IV',
    emoji: '👑',
    arcano: 'mayor',
    palabrasClave: ['Estructura', 'Autoridad', 'Liderazgo', 'Estabilidad', 'Control'],
    descripcion: 'El Emperador construye imperios sobre bases sólidas. Representa la autoridad que nace de la disciplina, la estructura que hace posible la libertad.',
    mensaje: 'Es momento de tomar las riendas con firmeza y claridad. Establecé límites, creá estructura. Tu fuerza interior es la base sobre la que todo lo demás se construye.',
  },
  {
    index: 5,
    nombre: 'El Hierofante',
    numeral: 'V',
    emoji: '⛪',
    arcano: 'mayor',
    palabrasClave: ['Tradición', 'Enseñanza', 'Espiritualidad', 'Convención', 'Guía'],
    descripcion: 'El Hierofante es el puente entre lo divino y lo humano. Representa la sabiduría que se transmite de generación en generación, la tradición como camino de evolución.',
    mensaje: 'Hoy puede haber un mensaje importante viniendo de una figura de guía, un maestro o una tradición. Escuchá con mente abierta — hay sabiduría en lo establecido.',
  },
  {
    index: 6,
    nombre: 'Los Amantes',
    numeral: 'VI',
    emoji: '💫',
    arcano: 'mayor',
    palabrasClave: ['Amor', 'Elección', 'Alineación', 'Valores', 'Unión'],
    descripcion: 'Los Amantes van más allá del amor romántico: hablan de la integración de opuestos dentro de uno mismo y del poder de elegir desde el corazón.',
    mensaje: 'Hoy te invita a elegir desde el amor, no desde el miedo. Las decisiones que tomes ahora siembran el futuro que querés vivir. Confiá en lo que tu corazón ya sabe.',
  },
  {
    index: 7,
    nombre: 'El Carro',
    numeral: 'VII',
    emoji: '⚡',
    arcano: 'mayor',
    palabrasClave: ['Determinación', 'Control', 'Victoria', 'Voluntad', 'Dirección'],
    descripcion: 'El Carro avanza con fuerza cuando sus opuestos internos están en armonía. Representa la victoria que se logra cuando domás tus propias contradicciones.',
    mensaje: 'Tenés la fuerza y la dirección para avanzar. No te detengas ante los obstáculos — hoy tu determinación es tu superpoder. El éxito llega para quien sigue.',
  },
  {
    index: 8,
    nombre: 'La Fuerza',
    numeral: 'VIII',
    emoji: '🦁',
    arcano: 'mayor',
    palabrasClave: ['Valentía', 'Paciencia', 'Compasión', 'Fuerza interior', 'Dominio suave'],
    descripcion: 'La Fuerza no doma al león con violencia sino con amor. Representa el poder que nace de la ternura, la valentía que coexiste con la vulnerabilidad.',
    mensaje: 'Tu mayor fortaleza hoy no es la dureza sino la gentileza. Tratate con compasión y tratá a los demás igual. La suavidad que mostrás es una forma de coraje.',
  },
  {
    index: 9,
    nombre: 'El Ermitaño',
    numeral: 'IX',
    emoji: '🏔️',
    arcano: 'mayor',
    palabrasClave: ['Soledad', 'Introspección', 'Guía interior', 'Búsqueda', 'Sabiduría'],
    descripcion: 'El Ermitaño lleva su propia luz en la oscuridad. Representa el camino hacia adentro, la sabiduría que solo se encuentra en el silencio y la soledad elegida.',
    mensaje: 'Retirarte un poco del ruido hoy puede darte más claridad que mil conversaciones. Tu luz interior es tu mejor guía. No temás estar sola con vos misma.',
  },
  {
    index: 10,
    nombre: 'La Rueda de la Fortuna',
    numeral: 'X',
    emoji: '🎡',
    arcano: 'mayor',
    palabrasClave: ['Ciclos', 'Destino', 'Cambio', 'Suerte', 'Oportunidad'],
    descripcion: 'La Rueda gira eternamente. Lo que sube baja y lo que baja vuelve a subir. Representa los ciclos inevitables de la existencia y la sabiduría de fluir con ellos.',
    mensaje: 'Todo está en movimiento hoy. Si estás en un momento difícil, recuerda que la rueda gira. Si estás en un pico, aprovechá y agradecé. Todo cambia — esa es la única constante.',
  },
  {
    index: 11,
    nombre: 'La Justicia',
    numeral: 'XI',
    emoji: '⚖️',
    arcano: 'mayor',
    palabrasClave: ['Equilibrio', 'Verdad', 'Causa y efecto', 'Claridad', 'Responsabilidad'],
    descripcion: 'La Justicia sostiene la balanza con mano firme. Representa la verdad objetiva, el karma que devuelve a cada uno según sus acciones.',
    mensaje: 'Las decisiones de hoy tienen peso real. Actuá con integridad y honestidad — con vos misma primero. Lo que siembres con justicia y verdad, crecerá sólido.',
  },
  {
    index: 12,
    nombre: 'El Colgado',
    numeral: 'XII',
    emoji: '🙃',
    arcano: 'mayor',
    palabrasClave: ['Pausa', 'Rendición', 'Nueva perspectiva', 'Sacrificio', 'Iluminación'],
    descripcion: 'El Colgado eligió su posición. Desde arriba hacia abajo el mundo se ve diferente. Representa la sabiduría que llega cuando soltamos el control y cambiamos de perspectiva.',
    mensaje: 'A veces la mejor acción es no actuar. Pausá, respirá, mirá la situación desde otro ángulo. Lo que parece un obstáculo puede ser una invitación a soltar y ver más claro.',
  },
  {
    index: 13,
    nombre: 'La Muerte',
    numeral: 'XIII',
    emoji: '🦋',
    arcano: 'mayor',
    palabrasClave: ['Transformación', 'Final', 'Transición', 'Cambio', 'Renacimiento'],
    descripcion: 'La Muerte en el tarot rara vez habla de muerte literal. Es la transformación más profunda, el final necesario que hace posible el nuevo comienzo.',
    mensaje: 'Algo está terminando para que algo mejor pueda nacer. No te aferres a lo que ya cumplió su ciclo. La mariposa no llora por dejar de ser oruga — confía en tu transformación.',
  },
  {
    index: 14,
    nombre: 'La Templanza',
    numeral: 'XIV',
    emoji: '🌊',
    arcano: 'mayor',
    palabrasClave: ['Equilibrio', 'Moderación', 'Paciencia', 'Alquimia', 'Armonía'],
    descripcion: 'La Templanza mezcla con maestría lo que parecía incompatible. Representa el arte de encontrar el punto medio, la alquimia que transforma opuestos en armonía.',
    mensaje: 'Hoy encontrás tu centro entre los extremos. No todo es blanco o negro — hay una mezcla perfecta esperándote. Paciencia y equilibrio son tus aliados.',
  },
  {
    index: 15,
    nombre: 'El Diablo',
    numeral: 'XV',
    emoji: '🔗',
    arcano: 'mayor',
    palabrasClave: ['Sombra', 'Adicción', 'Materialismo', 'Ilusión', 'Liberación posible'],
    descripcion: 'El Diablo muestra las cadenas que nos pusimos nosotros mismos. Representa las ataduras que creemos necesarias y los patrones que nos limitan sin que lo veamos.',
    mensaje: 'Hay algo que te tiene atada más de lo que reconocés. Hoy es un buen día para mirar esos patrones con honestidad. Las cadenas que ves en esta carta... se pueden soltar.',
  },
  {
    index: 16,
    nombre: 'La Torre',
    numeral: 'XVI',
    emoji: '⚡',
    arcano: 'mayor',
    palabrasClave: ['Revelación', 'Colapso', 'Caos', 'Verdad', 'Liberación súbita'],
    descripcion: 'La Torre cae para revelar lo que había debajo. Representa la destrucción de lo que se construyó sobre bases falsas y la libertad que llega después del caos.',
    mensaje: 'Algo puede derrumbarse hoy — pero lo que cae es lo que no era real. Bajo el caos hay una verdad liberadora esperando. No temas al rayo; teme quedarte en una torre hueca.',
  },
  {
    index: 17,
    nombre: 'La Estrella',
    numeral: 'XVII',
    emoji: '⭐',
    arcano: 'mayor',
    palabrasClave: ['Esperanza', 'Inspiración', 'Renovación', 'Fe', 'Serenidad'],
    descripcion: 'La Estrella brilla después de la tormenta. Representa la esperanza que persiste cuando todo lo demás falla, la fe en que el universo tiene un plan amoroso.',
    mensaje: 'Sos guiada. Aunque no lo veas claramente, hay una luz orientándote. Hoy es día de confiar, de sanar, de creer en lo que viene. La estrella brilla especialmente para vos.',
  },
  {
    index: 18,
    nombre: 'La Luna',
    numeral: 'XVIII',
    emoji: '🌙',
    arcano: 'mayor',
    palabrasClave: ['Ilusión', 'Miedos', 'Subconsciente', 'Sueños', 'Lo oculto'],
    descripcion: 'La Luna ilumina lo que preferíamos no ver. Representa el reino del subconsciente, los miedos que distorsionan la realidad y los sueños que traen mensajes.',
    mensaje: 'No todo es lo que parece hoy. Prestá atención a tus sueños y a lo que sientes bajo la superficie. Algún miedo puede estar coloreando tu percepción — miralo de frente.',
  },
  {
    index: 19,
    nombre: 'El Sol',
    numeral: 'XIX',
    emoji: '☀️',
    arcano: 'mayor',
    palabrasClave: ['Alegría', 'Éxito', 'Vitalidad', 'Claridad', 'Abundancia'],
    descripcion: 'El Sol es la carta más luminosa del mazo. Representa la alegría genuina, el éxito que viene de ser auténtica, la vitalidad que surge cuando vivimos en la luz.',
    mensaje: '¡Que brille tu luz hoy! Es un día de alegría, claridad y abundancia. Salí, celebrá, sé visible. Tu autenticidad es tu mayor poder ahora mismo.',
  },
  {
    index: 20,
    nombre: 'El Juicio',
    numeral: 'XX',
    emoji: '🎺',
    arcano: 'mayor',
    palabrasClave: ['Renacimiento', 'Llamado', 'Absolución', 'Reflexión', 'Despertar'],
    descripcion: 'El Juicio es el llamado al despertar. Representa el momento en que escuchamos nuestra vocación más profunda y respondemos con todo nuestro ser.',
    mensaje: 'Hay un llamado profundo resonando en vos. ¿Podés escucharlo? Hoy es un día de reflexión honesta sobre quién sos y quién querés ser. El perdón — propio y ajeno — libera.',
  },
  {
    index: 21,
    nombre: 'El Mundo',
    numeral: 'XXI',
    emoji: '🌍',
    arcano: 'mayor',
    palabrasClave: ['Completud', 'Integración', 'Logro', 'Totalidad', 'Celebración'],
    descripcion: 'El Mundo es la culminación del viaje del Loco. Representa la completud, la integración de todas las partes de uno mismo y el logro que viene de ese proceso.',
    mensaje: 'Estás llegando a un punto de completud. Celebrá lo que lograste, integrá lo que aprendiste. Un ciclo hermoso se cierra para que uno aún más rico pueda comenzar.',
  },

  // ═══════════════════════════════
  // ARCANOS MENORES — COPAS (22-35)
  // ═══════════════════════════════
  {
    index: 22,
    nombre: 'As de Copas',
    numeral: 'As',
    emoji: '🏆',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Amor nuevo', 'Emoción', 'Intuición', 'Apertura', 'Conexión'],
    descripcion: 'El As de Copas es el inicio de todo amor. Un corazón que se abre, una emoción que florece, la posibilidad de una conexión profunda.',
    mensaje: 'Tu corazón está listo para recibir. Abrilo sin miedo hoy — al amor, a la belleza, a la conexión. Algo hermoso está fluyendo hacia vos.',
  },
  {
    index: 23,
    nombre: 'Dos de Copas',
    numeral: 'II',
    emoji: '💑',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Unión', 'Partnership', 'Reciprocidad', 'Conexión', 'Armonía'],
    descripcion: 'El Dos de Copas celebra el encuentro entre dos almas. Representa la reciprocidad, el amor que fluye en ambas direcciones.',
    mensaje: 'Una conexión significativa está en el centro de tu día. Nutrila, honrala. Las relaciones que se cuidan con amor y respeto son el mayor tesoro.',
  },
  {
    index: 24,
    nombre: 'Tres de Copas',
    numeral: 'III',
    emoji: '🥂',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Celebración', 'Amistad', 'Comunidad', 'Alegría', 'Gratitud'],
    descripcion: 'El Tres de Copas es la fiesta del alma. Representa la alegría compartida, la amistad que nutre y los momentos de celebración genuina.',
    mensaje: 'Hoy es día de celebrar con quienes amás. La alegría compartida se multiplica. Agradecé tu tribu — esas personas que te sostienen y te hacen reír.',
  },
  {
    index: 25,
    nombre: 'Cuatro de Copas',
    numeral: 'IV',
    emoji: '😶',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Contemplación', 'Apatía', 'Introspección', 'Oportunidad perdida', 'Aburrimiento'],
    descripcion: 'El Cuatro de Copas muestra a alguien tan absorto en sus pensamientos que no ve la copa que le ofrecen. A veces la respuesta está justo frente a nosotros.',
    mensaje: '¿Estás tan metida en tus pensamientos que no ves lo que se te ofrece? Levantá la vista. Puede haber una oportunidad o una persona que esperás sin verla.',
  },
  {
    index: 26,
    nombre: 'Cinco de Copas',
    numeral: 'V',
    emoji: '😢',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Pérdida', 'Duelo', 'Decepción', 'Perspectiva', 'Esperanza'],
    descripcion: 'El Cinco de Copas llora sobre lo derramado pero olvida las copas que siguen en pie. Representa el duelo y la invitación a ver lo que todavía tenemos.',
    mensaje: 'Está bien llorar lo que se perdió. Pero cuando estés lista, girá y mirá lo que sigue en pie. No todo se fue — hay amor y posibilidades que todavía te esperan.',
  },
  {
    index: 27,
    nombre: 'Seis de Copas',
    numeral: 'VI',
    emoji: '🌼',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Nostalgia', 'Infancia', 'Inocencia', 'Recuerdos', 'Generosidad'],
    descripcion: 'El Seis de Copas regresa al jardín de la infancia. Representa la nostalgia sanadora, la inocencia que nunca se pierde del todo y la generosidad del corazón.',
    mensaje: 'Algo del pasado visita tu presente hoy — un recuerdo, una persona, una sensación. Recibilo con ternura. Tu niña interior tiene algo que enseñarte.',
  },
  {
    index: 28,
    nombre: 'Siete de Copas',
    numeral: 'VII',
    emoji: '✨',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Ilusión', 'Elección', 'Fantasía', 'Confusión', 'Deseos'],
    descripcion: 'El Siete de Copas presenta múltiples opciones, algunas reales y otras ilusorias. Representa el momento de elegir entre la fantasía y la realidad.',
    mensaje: 'Tenés muchas opciones frente a vos pero no todas son lo que parecen. Discernimiento es la clave hoy. ¿Cuál de estos caminos es real y cuál es solo una ilusión bonita?',
  },
  {
    index: 29,
    nombre: 'Ocho de Copas',
    numeral: 'VIII',
    emoji: '🚶‍♀️',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Abandono', 'Búsqueda', 'Dejar ir', 'Camino propio', 'Valentía'],
    descripcion: 'El Ocho de Copas deja atrás lo que ya no nutre para buscar algo más profundo. Requiere valentía dejar lo conocido pero cómodo por lo desconocido pero verdadero.',
    mensaje: 'Algo ya cumplió su función en tu vida. Está bien dejarlo y seguir buscando algo más alineado con quien sos ahora. La valentía de partir es la valentía de crecer.',
  },
  {
    index: 30,
    nombre: 'Nueve de Copas',
    numeral: 'IX',
    emoji: '🌟',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Satisfacción', 'Deseo cumplido', 'Bienestar', 'Placer', 'Gratitud'],
    descripcion: 'El Nueve de Copas es la carta del deseo cumplido. Representa la satisfacción genuina, el bienestar que viene de saber que lo que pediste está llegando.',
    mensaje: 'Tus deseos están en proceso de manifestarse. Hoy sentís — o podés sentir — una satisfacción genuina. Agradecé lo que tenés y confiá en lo que viene.',
  },
  {
    index: 31,
    nombre: 'Diez de Copas',
    numeral: 'X',
    emoji: '🌈',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Felicidad', 'Familia', 'Armonía', 'Amor completo', 'Bendición'],
    descripcion: 'El Diez de Copas es el final feliz del amor. Representa la completud emocional, la armonía en el hogar y el amor que se expande para abarcar todo.',
    mensaje: 'La felicidad verdadera está más cerca de lo que creés. Mirá a tu alrededor — hay amor, hay armonía, hay bendiciones. Permitite recibirlas con el corazón abierto.',
  },
  {
    index: 32,
    nombre: 'Paje de Copas',
    numeral: 'Paje',
    emoji: '🐟',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Mensaje emotivo', 'Creatividad', 'Sensibilidad', 'Intuición', 'Novedad'],
    descripcion: 'El Paje de Copas trae mensajes del corazón. Representa la sensibilidad creativa, la intuición que se abre y los mensajes inesperados del alma.',
    mensaje: 'Un mensaje emotivo o una inspiración creativa puede llegar hoy de manera inesperada. Mantenete abierta a lo que el corazón quiere decirte.',
  },
  {
    index: 33,
    nombre: 'Caballero de Copas',
    numeral: 'Caballero',
    emoji: '🐴',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Romance', 'Encanto', 'Creatividad', 'Imaginación', 'Propuesta'],
    descripcion: 'El Caballero de Copas llega con el corazón en la mano. Representa el romance idealizado, la creatividad que fluye y la propuesta que viene del alma.',
    mensaje: 'El romance y la creatividad están especialmente activos hoy. Seguí lo que te encanta con pasión. O prestá atención si alguien llega con una propuesta del corazón.',
  },
  {
    index: 34,
    nombre: 'Reina de Copas',
    numeral: 'Reina',
    emoji: '👸',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Empatía', 'Intuición', 'Compasión', 'Sabiduría emocional', 'Cuidado'],
    descripcion: 'La Reina de Copas escucha con el corazón. Representa la sabiduría emocional, la empatía profunda y la capacidad de sostener el espacio para los demás.',
    mensaje: 'Tu capacidad de sentir y sostener a otros es un don hoy. Confiá en tu intuición emocional — es más sabia que cualquier análisis. Y recordá también sostenerte a vos misma.',
  },
  {
    index: 35,
    nombre: 'Rey de Copas',
    numeral: 'Rey',
    emoji: '🤴',
    arcano: 'menor',
    palo: 'Copas',
    palabrasClave: ['Equilibrio emocional', 'Diplomacia', 'Madurez', 'Compasión', 'Liderazgo'],
    descripcion: 'El Rey de Copas gobierna sus emociones sin reprimirlas. Representa la madurez emocional que permite liderar con compasión y tomar decisiones desde el corazón.',
    mensaje: 'Hoy podés ser ese faro de calma y compasión que otros necesitan. Tu madurez emocional es tu liderazgo. Tomá decisiones desde el corazón con cabeza tranquila.',
  },

  // ═══════════════════════════════
  // ARCANOS MENORES — OROS (36-49)
  // ═══════════════════════════════
  {
    index: 36,
    nombre: 'As de Oros',
    numeral: 'As',
    emoji: '🪙',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Prosperidad', 'Oportunidad material', 'Abundancia', 'Nuevo inicio', 'Seguridad'],
    descripcion: 'El As de Oros abre la puerta a la prosperidad. Una nueva oportunidad material, un comienzo financiero prometedor o una semilla de abundancia.',
    mensaje: 'Una oportunidad concreta y prometedora está disponible. Ponela en tierra — con pasos reales y concretos. La abundancia comienza con un primer movimiento tangible.',
  },
  {
    index: 37,
    nombre: 'Dos de Oros',
    numeral: 'II',
    emoji: '⚖️',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Equilibrio', 'Adaptabilidad', 'Malabarismo', 'Flexibilidad', 'Cambio'],
    descripcion: 'El Dos de Oros hace malabares con gracia. Representa la capacidad de mantener el equilibrio cuando múltiples demandas compiten por tu atención.',
    mensaje: 'Estás haciendo malabarismos con varias responsabilidades. Está bien — tenés lo que se necesita para mantener el equilibrio. Sé flexible y tomá las cosas de a una.',
  },
  {
    index: 38,
    nombre: 'Tres de Oros',
    numeral: 'III',
    emoji: '🏗️',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Trabajo en equipo', 'Habilidad', 'Colaboración', 'Construcción', 'Reconocimiento'],
    descripcion: 'El Tres de Oros construye con otros. Representa la maestría que se desarrolla con práctica y la colaboración que multiplica los talentos individuales.',
    mensaje: 'Tu trabajo y habilidad son reconocidos. Colaborar con otros amplifica lo que podés lograr sola. Es un buen día para construir algo concreto y valioso.',
  },
  {
    index: 39,
    nombre: 'Cuatro de Oros',
    numeral: 'IV',
    emoji: '💰',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Seguridad', 'Control', 'Ahorro', 'Apego', 'Estabilidad'],
    descripcion: 'El Cuatro de Oros sostiene lo que tiene con fuerza. Puede ser prudencia saludable o miedo a perder que impide el flujo natural de la abundancia.',
    mensaje: 'Cuidar lo que tenés es sabio, pero aferrarte por miedo te estanca. Hay una diferencia entre seguridad y escasez mental. ¿Desde cuál estás actuando hoy?',
  },
  {
    index: 40,
    nombre: 'Cinco de Oros',
    numeral: 'V',
    emoji: '❄️',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Dificultad', 'Escasez', 'Aislamiento', 'Ayuda disponible', 'Adversidad'],
    descripcion: 'El Cinco de Oros camina en el frío mirando hacia el suelo, sin ver la luz que brilla dentro de la iglesia. A veces la ayuda está más cerca de lo que parece.',
    mensaje: 'Si estás atravesando dificultades, recordá que no estás sola y que la ayuda puede estar más cerca de lo que ves. Levantá la vista — hay calidez disponible para vos.',
  },
  {
    index: 41,
    nombre: 'Seis de Oros',
    numeral: 'VI',
    emoji: '🤝',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Generosidad', 'Dar y recibir', 'Caridad', 'Prosperidad compartida', 'Gratitud'],
    descripcion: 'El Seis de Oros comparte con generosidad. Representa el flujo natural de la abundancia que crece cuando se da y se recibe con gracia.',
    mensaje: 'La generosidad fluye hoy en ambas direcciones. Dar sin esperar y recibir sin culpa son dos caras del mismo flujo. La abundancia real se comparte.',
  },
  {
    index: 42,
    nombre: 'Siete de Oros',
    numeral: 'VII',
    emoji: '🌱',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Paciencia', 'Inversión', 'Evaluación', 'Crecimiento lento', 'Perseverancia'],
    descripcion: 'El Siete de Oros contempla el jardín que plantó. Todavía no es tiempo de cosechar — es tiempo de evaluar y tener paciencia con el proceso.',
    mensaje: 'Lo que sembraste está creciendo aunque no lo veas aún. La paciencia es la herramienta más poderosa que tenés ahora. Seguí regando sin exigir frutos inmediatos.',
  },
  {
    index: 43,
    nombre: 'Ocho de Oros',
    numeral: 'VIII',
    emoji: '🔨',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Dedicación', 'Oficio', 'Aprendizaje', 'Detalle', 'Mejora continua'],
    descripcion: 'El Ocho de Oros trabaja con dedicación meticulosa. Representa el aprendizaje de un oficio, la mejora continua y el orgullo de hacer las cosas bien.',
    mensaje: 'La excelencia llega con práctica y dedicación. Hoy es día de enfocarte en los detalles y hacer tu trabajo con orgullo. La maestría se construye ladrillo a ladrillo.',
  },
  {
    index: 44,
    nombre: 'Nueve de Oros',
    numeral: 'IX',
    emoji: '🌺',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Independencia', 'Lujo', 'Logro', 'Autosuficiencia', 'Refinamiento'],
    descripcion: 'El Nueve de Oros disfruta de los frutos de su trabajo con elegancia. Representa la independencia ganada con esfuerzo y el placer de disfrutarla.',
    mensaje: 'Merecés disfrutar de lo que construiste. Hoy permítite el pequeño lujo, la pausa placentera, el orgullo tranquilo de lo que lograste con tu propio esfuerzo.',
  },
  {
    index: 45,
    nombre: 'Diez de Oros',
    numeral: 'X',
    emoji: '🏡',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Legado', 'Familia', 'Riqueza', 'Tradición', 'Seguridad duradera'],
    descripcion: 'El Diez de Oros es la abundancia que trasciende generaciones. Representa el legado familiar, la seguridad duradera y la riqueza en todos sus sentidos.',
    mensaje: 'Pensá en lo que estás construyendo más allá de vos misma. El legado que dejás — de amor, de valores, de trabajo — es la riqueza más real que existe.',
  },
  {
    index: 46,
    nombre: 'Paje de Oros',
    numeral: 'Paje',
    emoji: '📚',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Estudio', 'Oportunidad', 'Aprendizaje práctico', 'Comienzo', 'Diligencia'],
    descripcion: 'El Paje de Oros estudia con atención y dedicación. Representa las oportunidades que vienen del aprendizaje y la disposición a comenzar desde cero.',
    mensaje: 'Es momento de aprender algo nuevo o de comprometerte con mayor diligencia con lo que ya estás estudiando. Una oportunidad práctica puede presentarse hoy.',
  },
  {
    index: 47,
    nombre: 'Caballero de Oros',
    numeral: 'Caballero',
    emoji: '🐎',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Constancia', 'Responsabilidad', 'Trabajo duro', 'Metódico', 'Confiable'],
    descripcion: 'El Caballero de Oros avanza despacio pero sin detenerse. Representa la confiabilidad, el trabajo metódico y la responsabilidad que construye cosas duraderas.',
    mensaje: 'No se trata de velocidad sino de constancia. Hoy avanzá con pasos seguros aunque lentos. La responsabilidad y el compromiso con tu trabajo son tu mayor fortaleza.',
  },
  {
    index: 48,
    nombre: 'Reina de Oros',
    numeral: 'Reina',
    emoji: '👑',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Abundancia', 'Practicidad', 'Nurturing', 'Seguridad', 'Generosidad'],
    descripcion: 'La Reina de Oros crea abundancia a su alrededor con gracia natural. Representa la practicidad que nutre, la generosidad que prospera y la seguridad que se comparte.',
    mensaje: 'Tu capacidad de crear bienestar concreto para vos y para quienes amás es un superpoder. Hoy expresalo — con comida, con calidez, con generosidad práctica.',
  },
  {
    index: 49,
    nombre: 'Rey de Oros',
    numeral: 'Rey',
    emoji: '💎',
    arcano: 'menor',
    palo: 'Oros',
    palabrasClave: ['Éxito', 'Liderazgo', 'Abundancia', 'Seguridad', 'Poder material'],
    descripcion: 'El Rey de Oros gobierna el mundo material con maestría. Representa el éxito ganado con trabajo, el liderazgo generoso y la abundancia que se administra con sabiduría.',
    mensaje: 'Tenés la capacidad de crear seguridad y abundancia real. Liderá con generosidad hoy — tanto en lo económico como en lo concreto. Tu estabilidad sostiene a otros.',
  },

  // ═══════════════════════════════
  // ARCANOS MENORES — ESPADAS (50-63)
  // ═══════════════════════════════
  {
    index: 50,
    nombre: 'As de Espadas',
    numeral: 'As',
    emoji: '⚔️',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Claridad', 'Verdad', 'Breakthrough', 'Justicia', 'Nueva idea'],
    descripcion: 'El As de Espadas corta con precisión quirúrgica la confusión. Representa la claridad mental absoluta, la verdad que irrumpe y la idea que cambia todo.',
    mensaje: 'Una claridad poderosa puede llegar hoy — una verdad que corta, una idea que transforma. Abrite a verla aunque sea incómoda. La verdad siempre libera.',
  },
  {
    index: 51,
    nombre: 'Dos de Espadas',
    numeral: 'II',
    emoji: '🙈',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Bloqueo', 'Decisión difícil', 'Negación', 'Equilibrio tenso', 'Dilema'],
    descripcion: 'El Dos de Espadas tiene los ojos vendados ante una decisión difícil. Representa el estancamiento que viene de no querer ver y la tensión de la elección postergada.',
    mensaje: 'Hay algo que preferís no ver porque la decisión es difícil. Pero seguir con los ojos cerrados no resuelve el dilema. Quitá la venda — lo que hay del otro lado es manejable.',
  },
  {
    index: 52,
    nombre: 'Tres de Espadas',
    numeral: 'III',
    emoji: '💔',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Dolor', 'Pérdida', 'Tristeza', 'Herida', 'Procesamiento'],
    descripcion: 'El Tres de Espadas muestra el corazón atravesado. Representa el dolor genuino que viene de pérdidas, separaciones o traiciones — y la necesidad de sentirlo.',
    mensaje: 'Hay dolor real aquí y está bien sentirlo. No lo bypasees — lo que no se siente no se sana. Llorá si necesitás. Al otro lado del dolor genuino hay sanación.',
  },
  {
    index: 53,
    nombre: 'Cuatro de Espadas',
    numeral: 'IV',
    emoji: '😴',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Descanso', 'Recuperación', 'Pausa', 'Meditación', 'Retiro'],
    descripcion: 'El Cuatro de Espadas descansa después de la batalla. Representa la necesidad vital del descanso y la recuperación después de un período de esfuerzo o lucha.',
    mensaje: 'Tu mente y tu cuerpo necesitan pausa. No es rendirse — es recuperar fuerzas para lo que viene. Date permiso de descansar, meditar y reponer energía hoy.',
  },
  {
    index: 54,
    nombre: 'Cinco de Espadas',
    numeral: 'V',
    emoji: '😤',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Conflicto', 'Derrota', 'Victoria pírrica', 'Ego', 'Consecuencias'],
    descripcion: 'El Cinco de Espadas gana la batalla pero pierde algo más importante. Representa los conflictos donde ganar no siempre vale lo que cuesta.',
    mensaje: '¿Vale la pena esta pelea? A veces ganar un argumento significa perder una relación. Antes de insistir en tener razón, preguntate qué querés preservar realmente.',
  },
  {
    index: 55,
    nombre: 'Seis de Espadas',
    numeral: 'VI',
    emoji: '⛵',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Transición', 'Alejarse', 'Aguas más calmas', 'Sanación', 'Movimiento'],
    descripcion: 'El Seis de Espadas navega hacia aguas más calmas. Representa el movimiento desde un lugar de turbulencia hacia un espacio más tranquilo y sanador.',
    mensaje: 'Estás pasando de aguas turbulentas a aguas más calmas. La transición puede ser lenta pero la dirección es buena. Seguí remando — el horizonte es más tranquilo.',
  },
  {
    index: 56,
    nombre: 'Siete de Espadas',
    numeral: 'VII',
    emoji: '🦊',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Estrategia', 'Engaño', 'Astucia', 'Evasión', 'Mente astuta'],
    descripcion: 'El Siete de Espadas actúa con astucia, a veces con engaño. Puede representar la estrategia inteligente o la deshonestidad que eventualmente se descubre.',
    mensaje: 'sSé honesta — con vos misma primero. ¿Hay algo que estés evitando enfrentar directamente? La astucia tiene su lugar, pero la honestidad siempre construye más sólido.',
  },
  {
    index: 57,
    nombre: 'Ocho de Espadas',
    numeral: 'VIII',
    emoji: '🪢',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Trampa mental', 'Limitación auto-impuesta', 'Miedo', 'Parálisis', 'Liberación posible'],
    descripcion: 'El Ocho de Espadas está atada pero las espadas no la tocan. Representa las limitaciones que creemos reales pero que en parte son construcciones de nuestra mente.',
    mensaje: 'Te sentís atrapada pero las cadenas son más mentales que reales. La solución está más cerca de lo que creés. Un pequeño movimiento puede cambiar todo.',
  },
  {
    index: 58,
    nombre: 'Nueve de Espadas',
    numeral: 'IX',
    emoji: '😰',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Ansiedad', 'Pesadillas', 'Preocupación', 'Pensamiento catastrófico', 'Culpa'],
    descripcion: 'El Nueve de Espadas se despierta en la noche con angustia. Representa la ansiedad mental, los pensamientos que se magnifican en la oscuridad.',
    mensaje: 'La mente puede crear monstruos que no existen. Si la ansiedad te visita hoy, recordá: no todo lo que temés va a pasar. Respirá. El amanecer siempre llega.',
  },
  {
    index: 59,
    nombre: 'Diez de Espadas',
    numeral: 'X',
    emoji: '🌅',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Final doloroso', 'Traición', 'Colapso', 'Nuevo amanecer', 'Toque de fondo'],
    descripcion: 'El Diez de Espadas toca fondo — pero en el horizonte amanece. Representa el final más difícil, que sin embargo abre el camino a un nuevo comienzo.',
    mensaje: 'Esto también pasa. Lo que parece el peor momento puede ser el punto de inflexión. El amanecer en el horizonte de esta carta es real — miralo.',
  },
  {
    index: 60,
    nombre: 'Paje de Espadas',
    numeral: 'Paje',
    emoji: '🔍',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Curiosidad', 'Vigilancia', 'Comunicación', 'Ideas nuevas', 'Mente activa'],
    descripcion: 'El Paje de Espadas observa con agudeza e inquietud mental. Representa la curiosidad que todo lo cuestiona, la mente ágil que busca respuestas.',
    mensaje: 'Tu mente está especialmente activa y curiosa hoy. Hacé las preguntas difíciles. Investigá. Comunicá tus ideas. La verdad surge de quienes se atreven a preguntar.',
  },
  {
    index: 61,
    nombre: 'Caballero de Espadas',
    numeral: 'Caballero',
    emoji: '⚡',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Acción rápida', 'Ambición', 'Impulsividad', 'Determinación', 'Mente veloz'],
    descripcion: 'El Caballero de Espadas carga a toda velocidad. Representa la acción veloz y determinada, que puede ser brillante o impulsiva según el momento.',
    mensaje: 'Tu energía está activa y poderosa. Actuá con determinación pero tomá un segundo antes de lanzarte — la velocidad es tuya, solo asegurate de apuntar bien.',
  },
  {
    index: 62,
    nombre: 'Reina de Espadas',
    numeral: 'Reina',
    emoji: '🗡️',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Claridad mental', 'Independencia', 'Verdad directa', 'Sabiduría', 'Agudeza'],
    descripcion: 'La Reina de Espadas ve con claridad implacable. Representa la mente que corta la confusión, la honestidad directa y la independencia que viene de conocerse.',
    mensaje: 'Tu mente está afilada hoy. Di la verdad con claridad y compasión. No te enredes en lo que otros esperan — tu perspectiva directa es exactamente lo que se necesita.',
  },
  {
    index: 63,
    nombre: 'Rey de Espadas',
    numeral: 'Rey',
    emoji: '⚖️',
    arcano: 'menor',
    palo: 'Espadas',
    palabrasClave: ['Autoridad intelectual', 'Justicia', 'Verdad', 'Liderazgo mental', 'Decisión'],
    descripcion: 'El Rey de Espadas gobierna con la mente como cetro. Representa el liderazgo que viene de la claridad intelectual y la capacidad de tomar decisiones justas.',
    mensaje: 'Liderá con claridad y justicia hoy. Las decisiones difíciles te esperan — tomalas con la mente despejada y el corazón informado. Tu imparcialidad es tu mayor poder.',
  },

  // ═══════════════════════════════
  // ARCANOS MENORES — BASTOS (64-77)
  // ═══════════════════════════════
  {
    index: 64,
    nombre: 'As de Bastos',
    numeral: 'As',
    emoji: '🔥',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Inspiración', 'Potencial', 'Creatividad', 'Entusiasmo', 'Chispa'],
    descripcion: 'El As de Bastos es la chispa de todo lo que puede ser. Representa el entusiasmo desbordante de una nueva idea, proyecto o pasión que comienza.',
    mensaje: 'Una chispa de inspiración se enciende hoy. No la ignores ni la analices demasiado — actuá sobre ella mientras arde. La creatividad se alimenta de acción inmediata.',
  },
  {
    index: 65,
    nombre: 'Dos de Bastos',
    numeral: 'II',
    emoji: '🗺️',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Planificación', 'Visión', 'Expansión', 'Decisión futura', 'Potencial'],
    descripcion: 'El Dos de Bastos mira el horizonte con visión. Representa el momento de decidir hacia dónde ir, la planificación que precede a la gran aventura.',
    mensaje: 'El mundo está frente a vos esperando que elijas tu dirección. Hoy es día de soñar en grande y empezar a trazar el mapa. ¿Hacia dónde querés ir?',
  },
  {
    index: 66,
    nombre: 'Tres de Bastos',
    numeral: 'III',
    emoji: '⛵',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Expansión', 'Visión', 'Liderazgo', 'Empresa', 'Progreso'],
    descripcion: 'El Tres de Bastos ve sus barcos partir hacia el horizonte. Representa el comienzo de una expansión, el liderazgo que otros siguen y los primeros frutos del esfuerzo.',
    mensaje: 'Lo que pusiste en movimiento está tomando vuelo. Tus planes se expanden más allá de lo que imaginabas. Confiá en el proceso y seguí mirando hacia el horizonte.',
  },
  {
    index: 67,
    nombre: 'Cuatro de Bastos',
    numeral: 'IV',
    emoji: '🎊',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Celebración', 'Hogar', 'Estabilidad', 'Comunidad', 'Logro'],
    descripcion: 'El Cuatro de Bastos celebra con la comunidad. Representa la alegría de llegar a casa, el logro que se comparte y la estabilidad que permite la fiesta.',
    mensaje: '¡Celebrá! Algo merece ser festejado hoy — quizás un logro, una llegada, un reencuentro. El hogar y la comunidad son tu fuente de alegría real.',
  },
  {
    index: 68,
    nombre: 'Cinco de Bastos',
    numeral: 'V',
    emoji: '🥊',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Conflicto', 'Competencia', 'Caos', 'Desacuerdo', 'Energía'],
    descripcion: 'El Cinco de Bastos muestra el caos de múltiples energías chocando. Puede ser conflicto improductivo o la energía competitiva que te hace crecer.',
    mensaje: 'Hay mucha energía y quizás algo de caos o competencia en el ambiente. No te enredés en peleas innecesarias, pero tampoco te achiques. Tu energía bien dirigida gana.',
  },
  {
    index: 69,
    nombre: 'Seis de Bastos',
    numeral: 'VI',
    emoji: '🏆',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Victoria', 'Reconocimiento', 'Éxito', 'Logro público', 'Confianza'],
    descripcion: 'El Seis de Bastos desfila en victorioso. Representa el éxito que se hace visible, el reconocimiento merecido y la confianza que viene de un logro real.',
    mensaje: 'Tu éxito merece ser reconocido — y lo será. Recibí el reconocimiento con gracia. Hoy podés brillar sin disculparte por ello. Tu victoria inspira a otros.',
  },
  {
    index: 70,
    nombre: 'Siete de Bastos',
    numeral: 'VII',
    emoji: '🛡️',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Defensa', 'Perseverancia', 'Posición', 'Desafío', 'Valentía'],
    descripcion: 'El Siete de Bastos defiende su posición desde lo alto. Representa la valentía de mantener tu terreno cuando sientes que otros cuestionan lo que construiste.',
    mensaje: 'Defendé lo que creés con valentía. Puede sentirse como que todo te cuestiona, pero tenés el terreno alto — la experiencia y la convicción de tu lado. No cedas.',
  },
  {
    index: 71,
    nombre: 'Ocho de Bastos',
    numeral: 'VIII',
    emoji: '🚀',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Velocidad', 'Movimiento', 'Comunicación', 'Viaje', 'Acción rápida'],
    descripcion: 'El Ocho de Bastos vuela a toda velocidad. Representa el movimiento acelerado, las noticias que llegan rápido y la energía que por fin fluye sin obstáculos.',
    mensaje: 'Las cosas se mueven muy rápido hoy. Noticias, mensajes, oportunidades — todo llega junto. Mantenete ágil y aprovechá el momentum. Este viento no dura para siempre.',
  },
  {
    index: 72,
    nombre: 'Nueve de Bastos',
    numeral: 'IX',
    emoji: '🩹',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Resistencia', 'Perseverancia', 'Guardia alta', 'Cansancio', 'Casi llegando'],
    descripcion: 'El Nueve de Bastos está herido pero sigue de pie. Representa la resistencia que se mantiene aunque el cuerpo y el espíritu estén cansados — el último tramo antes de llegar.',
    mensaje: 'Estás cansada pero casi llegás. No te rindas ahora — la meta está más cerca de lo que se siente. Tu perseverancia es extraordinaria. Un paso más.',
  },
  {
    index: 73,
    nombre: 'Diez de Bastos',
    numeral: 'X',
    emoji: '😓',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Sobrecarga', 'Responsabilidad', 'Peso', 'Delegación necesaria', 'Fin cercano'],
    descripcion: 'El Diez de Bastos carga más de lo que puede sola. Representa la sobrecarga de responsabilidades y la necesidad urgente de soltar algunas o pedir ayuda.',
    mensaje: 'Estás cargando demasiado. No todo tiene que ser tuyo. Delegá, pedí ayuda, soltá lo que no es esencial. Llegar a destino cargada de todo no es el único camino.',
  },
  {
    index: 74,
    nombre: 'Paje de Bastos',
    numeral: 'Paje',
    emoji: '🌋',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Entusiasmo', 'Exploración', 'Noticias', 'Creatividad joven', 'Potencial'],
    descripcion: 'El Paje de Bastos llega con entusiasmo fresco e ideas nuevas. Representa la energía creativa sin filtros, la curiosidad que explora sin miedo.',
    mensaje: 'Una energía fresca y entusiasta llega hoy — puede ser una idea, una noticia o una persona. Recibila con apertura. El entusiasmo sin experiencia tiene su propio valor.',
  },
  {
    index: 75,
    nombre: 'Caballero de Bastos',
    numeral: 'Caballero',
    emoji: '🏇',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Aventura', 'Pasión', 'Impulsividad', 'Energía', 'Movimiento'],
    descripcion: 'El Caballero de Bastos galopa sin mirar atrás. Representa la pasión que se lanza sin calcular, la aventura que llama y la energía ardiente que no conoce límites.',
    mensaje: 'La pasión y la aventura te llaman. Respondé a ese llamado con todo — pero prestá atención al camino. El fuego que arde muy rápido puede consumirse pronto.',
  },
  {
    index: 76,
    nombre: 'Reina de Bastos',
    numeral: 'Reina',
    emoji: '🌻',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Carisma', 'Confianza', 'Creatividad', 'Determinación', 'Magnetismo'],
    descripcion: 'La Reina de Bastos irradia confianza y creatividad. Representa el carisma que atrae, la determinación que inspira y la calidez que hace que todo florezca.',
    mensaje: 'Tu energía es magnética hoy. La confianza que irradiás atrae lo que necesitás. Sé completamente vos misma — tu autenticidad es tu mayor poder.',
  },
  {
    index: 77,
    nombre: 'Rey de Bastos',
    numeral: 'Rey',
    emoji: '🦁',
    arcano: 'menor',
    palo: 'Bastos',
    palabrasClave: ['Liderazgo', 'Visión', 'Emprendimiento', 'Pasión madura', 'Inspiración'],
    descripcion: 'El Rey de Bastos lidera con visión y pasión madura. Representa el emprendedor que inspira, el líder carismático cuya visión enciende a quienes lo rodean.',
    mensaje: 'Tu visión y liderazgo están en su punto más alto. Es momento de inspirar a otros con tu entusiasmo y tu ejemplo. Liderá desde la pasión y la integridad.',
  },
]

/**
 * Obtiene el arcano del día para una usuaria específica
 * Usa un seed basado en el userId + fecha para que sea consistente
 * pero diferente para cada usuaria
 */
export function getCardOfTheDay(userId, date = new Date()) {
  const dateStr = `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`
  const seed = `${userId}-${dateStr}`

  // Hash simple del seed para obtener un índice consistente
  let hash = 0
  for (let i = 0; i < seed.length; i++) {
    const char = seed.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash // Convertir a 32bit integer
  }

  const index = Math.abs(hash) % TAROT_CARDS.length
  return TAROT_CARDS[index]
}
